/* Odia translations for the public page. English string is the key, so a
   label cannot exist in one language and be forgotten in the other; anything
   missing here falls back to the English rather than rendering blank. */
window.OR = {
  'Village fund · public account': 'ଗାଁ ବିତ୍ତ · ସାଧାରଣ ହିସାବ',
  'Committee sign-in': 'କମିଟି ଲଗିନ',
  'Fund available today': 'ଆଜି ଥିବା ବିତ୍ତ',
  'How it adds up': 'ହିସାବ ବିବରଣୀ',
  'How the village fund works': 'ଗାଁ ବିତ୍ତ କିପରି ଚଳେ',
  'Balance in hand': 'ହାତରେ ଥିବା ଟଙ୍କା',
  'The village': 'ଆମ ଗାଁ',
  'Families': 'ପରିବାର',
  'Members': 'ସଦସ୍ୟ',
  'Helped this year': 'ଏବର୍ଷ ସହାୟତା',
  'Support running': 'ଚାଲୁ ସହାୟତା',
  'Major expenses completed': 'ସମାପ୍ତ ବଡ ଖର୍ଚ୍ଚ',
  'Recent spending': 'ନିକଟର ଖର୍ଚ୍ଚ',
  'Occasion': 'ଅବସର',
  'Year': 'ବର୍ଷ',
  'Budget': 'ବଜେଟ',
  'Spent': 'ଖର୍ଚ୍ଚ ହେଲା',
  'Date': 'ତାରିଖ',
  'What for': 'କାହିଁକି',
  'Amount': 'ଟଙ୍କା',
  'Notice board': 'ସୂଚନା ପଟ୍ଟ',
  'In remembrance': 'ସ୍ମୃତି',
  'Days to remember': 'ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ଦିନ',
  'Raise / track a grievance': 'ଅଭିଯୋଗ ଦିଅନ୍ତୁ / ଦେଖନ୍ତୁ',
  'Grievance': 'ଅଭିଯୋଗ',
  'Raise a grievance': 'ଅଭିଯୋଗ ଦିଅନ୍ତୁ',
  'Track a grievance': 'ଅଭିଯୋଗ ଦେଖନ୍ତୁ',
  'How it is resolved': 'କିପରି ସମାଧାନ ହୁଏ',
  'Your name': 'ଆପଣଙ୍କ ନାଆଁ',
  'Full name': 'ପୂରା ନାଆଁ',
  'Mobile number': 'ମୋବାଇଲ ନମ୍ବର',
  'What is this about': 'କାହା ସମ୍ବନ୍ଧୀୟ',
  'Describe the problem': 'ସମସ୍ୟା ଲେଖନ୍ତୁ',
  'Submit grievance': 'ଦାଖଲ କରନ୍ତୁ',
  'Grievance number': 'ଅଭିଯୋଗ ନମ୍ବର',
  'Check status': 'ଅବସ୍ଥା ଦେଖନ୍ତୁ',
  'Received': 'ମିଳିଲା',
  'Under review': 'ବିଚାରାଧୀନ',
  'Action taken': 'କାର୍ଯ୍ୟକାରୀ ହେଲା',
  'Resolved': 'ସମାଧାନ ହେଲା',
  'Water': 'ପାଣି',
  'Road': 'ରାସ୍ତା',
  'Electricity': 'ବିଦ୍ୟୁତ',
  'Sanitation': 'ପରିଷ୍କାର',
  'Fund misuse': 'ବିତ୍ତ ଅପବ୍ୟବହାର',
  'Welfare benefit': 'କଲ୍ୟାଣ ସୁବିଧା',
  'Family record error': 'ପରିବାର ତଥ୍ୟ ଭୁଲ',
  'Other': 'ଅନ୍ୟ',
  'Print this page': 'ଏହି ପେଜ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
  'Try again': 'ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ',
  'post': 'ପୋଷ୍ଟ',
  'posts': 'ପୋଷ୍ଟ',
  'as on': 'ତାରିଖ',
  'Chanda from families': 'ପରିବାରଙ୍କ ଚାନ୍ଦା',
  'Each household pays a monthly share to the committee.': 'ପ୍ରତି ଘର ମାସିକ ଭାଗ କମିଟିକୁ ଦିଏ।',
  'Donations and interest': 'ଦାନ ଓ ସୁଧ',
  'Gifts from villagers and those living outside.': 'ଗାଁର ଓ ବାହାରେ ରହୁଥିବା ଲୋକଙ୍କ ଦାନ।',
  'Spent on the village': 'ଗାଁ ପାଇଁ ଖର୍ଚ୍ଚ',
  'Emergency help, medical and school support, repairs and festivals.': 'ଆପଦକାଳୀନ ସହାୟତା, ଚିକିତ୍ସା ଓ ପାଠପଢ଼ା, ମରାମତି ଓ ପର୍ବପର୍ବାଣି।',
  'Money the committee holds today, after everything recorded in the register.': 'ହିସାବ ବହିରେ ଲେଖା ସବୁ ପରେ ଆଜି କମିଟି ପାଖରେ ଥିବା ଟଙ୍କା।',
  'Nothing has been recorded in the fund register yet. This figure will move as soon as the committee enters the first contribution.': 'ହିସାବ ବହିରେ ଏପର୍ଯ୍ୟନ୍ତ କିଛି ଲେଖା ହୋଇନାହିଁ। କମିଟି ପ୍ରଥମ ଚାନ୍ଦା ଲେଖିବା ମାତ୍ରେ ଏହି ଅଙ୍କ ବଦଳିବ।',
  'Every rupee shown here is entered by the village committee in the fund register. If something looks wrong, tell any committee member.': 'ଏଠାରେ ଦେଖାଯାଉଥିବା ପ୍ରତି ଟଙ୍କା ଗାଁ କମିଟି ହିସାବ ବହିରେ ଲେଖିଛନ୍ତି। କିଛି ଭୁଲ ଲାଗିଲେ ଯେକୌଣସି କମିଟି ସଦସ୍ୟଙ୍କୁ କୁହନ୍ତୁ।',
  'Published by the Malipatana village committee. Figures come straight from the fund register.': 'ମାଳିପାଟଣା ଗାଁ କମିଟି ଦ୍ୱାରା ପ୍ରକାଶିତ। ଅଙ୍କ ସିଧା ହିସାବ ବହିରୁ ଆସେ।',
  'Loading the village account…': 'ଗାଁ ହିସାବ ଖୋଲୁଛି…',
  'This page reads the same sheet the committee uses.': 'ଏହି ପେଜ କମିଟି ବ୍ୟବହାର କରୁଥିବା ସେହି ସିଟ୍ ପଢ଼େ।',
  'Could not load the account just now': 'ଏହି ମୁହୂର୍ତ୍ତରେ ହିସାବ ଖୋଲିପାରିଲା ନାହିଁ',
  'The connection to the village register did not answer.': 'ଗାଁ ହିସାବ ବହି ସହ ଯୋଗାଯୋଗ ଉତ୍ତର ଦେଲା ନାହିଁ।'
};
